### ISSUE TITLE
SuperC config generation fails as .config file cannot be found

### ISSUE THREAD

**Issue by necipfazil** [paulgazz/kmax#127]
Reproduce:

```
# get linux source at linux/
cd linux/

# Make sure .config does not exist
rm .config

# Make sure we create a clean copy of super configs
git clean -fdx
make distclean

klocalizer -a x86_64 --include-mutex kernel/fork.o:[296]
```

Results in:
```
Traceback (most recent call last):
  File "/usr/local/bin/klocalizer", line 4, in <module>
    __import__('pkg_resources').run_script('kmax==3.0', 'klocalizer')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/kmax-3.0-py3.8-linux-x86_64.egg/EGG-INFO/scripts/klocalizer", line 1558, in <module>
    klocalizerCLI()
  File "/usr/local/lib/python3.8/dist-packages/kmax-3.0-py3.8-linux-x86_64.egg/EGG-INFO/scripts/klocalizer", line 1051, in klocalizerCLI
    get_presence_conditions(unit2srcfile(unit), arch)
  File "/usr/local/lib/python3.8/dist-packages/kmax-3.0-py3.8-linux-x86_64.egg/EGG-INFO/scripts/klocalizer", line 778, in get_presence_conditions
    config_exists = superc.ensure_superc_config(srcfile, superc_formulas_dir, linux_ksrc, arch, cross_compiler, build_targets, compile_jobs, build_timeout, logger)
  File "/usr/local/lib/python3.8/dist-packages/kmax-3.0-py3.8-linux-x86_64.egg/kmax/superc.py", line 466, in ensure_superc_config
    ret = self.create_superc_config_on_built_unit(srcfile, output_superc_configs_dir_path, linux_ksrc, arch.name, cross_compiler)
  File "/usr/local/lib/python3.8/dist-packages/kmax-3.0-py3.8-linux-x86_64.egg/kmax/superc.py", line 370, in create_superc_config_on_built_unit
    assert os.path.isfile(os.path.join(linux_ksrc, ".config"))
AssertionError
```

The assertion is that SuperC python module assumes a .config file exists at LINUX_KSRC/.config to be used for SuperC config generation, yet it does not exist.  The reason is that we keep the .config file elsewhere for future diagnostic purposes, but we don't have a copy at LINUX_KSRC/.config.

**Comment by necipfazil** [comment]
This resulted in about 1,000 assertions for our experiments on over 12,000 patches.
