### ISSUE TITLE
klocalizer can't create formulas on demand

### ISSUE THREAD

**Issue by necipfazil** [paulgazz/kmax#15]
OS: Ubuntu 20.04 LTS, Kernel: 5.4.0-42-generic
Python: 3.8.2

I installed kmax from source with kextractor next-20200430.

For [linux staging tree](https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/staging.git/) v5.9-rc1, when I run klocalizer for some compilation unit to let it create the formulas on demand and find some config, I face with an error:
`$ klocalizer drivers/usb/storage/alauda.o`
```
INFO: Kmax formula file: .kmax/kmax
INFO: No prebuilt kmax formulas.  Running kmax on demand.
INFO: Trying the following architectures: x86_64 i386 arm arm64 sparc64 sparc powerpc mips alpha arc c6x csky h8300 hexagon ia64 m68k microblaze nds32 nios2 openrisc parisc riscv s390 sh sh64 um um32 unicore32 xtensa
INFO: Using output file ".config".
INFO: drivers/ has no kmax formula, assuming it is unconstrained.
INFO: Trying "x86_64"
INFO: Kclause formulas file: .kmax/kclause/x86_64/kclause
INFO: Generating kclause formulas for x86_64.
INFO: Extracting Kconfig dependencies: kextractlinux x86_64 .kmax/kclause/x86_64/kextract.pending
Traceback (most recent call last):
  File "/usr/local/bin/klocalizer", line 4, in <module>
    __import__('pkg_resources').run_script('kmax==2.3rc1', 'klocalizer')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/kmax-2.3rc1-py3.8-linux-x86_64.egg/EGG-INFO/scripts/klocalizer", line 681, in <module>
    os.rename(kextract_file_pending, get_arch_kextract_file(formulas, arch))
FileNotFoundError: [Errno 2] No such file or directory: '.kmax/kclause/x86_64/kextract.pending' -> '.kmax/kclause/x86_64/kextract'
```

**Comment by paulgazz** [comment]
Fixed by #16
