### ISSUE TITLE
Linux stable 4.9.316 couldn't generate kextract file (kmax: v4.3.1, arch: riscv)

### ISSUE THREAD

**Issue by Yujie-Liu** [paulgazz/kmax#160]
reproduce:
```
$ cd linux
$ git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
$ git fetch stable linux-4.9.y
$ git checkout 95302ce6d8a08e88b7562238a8018820631325b6
HEAD is now at 95302ce6d8a0 Linux 4.9.316

$kismet -a riscv
INFO: Computing the build system id for the Linux source..
INFO: Build system id: b0c1822504e6
INFO: Kismet will analyze the select constructs of the architecture "riscv" for unmet direct dependency.
INFO: All times reported are measured using Python's time.perf_counter() utility.
INFO: Prefetching the architecture kclause formulas.
ERROR:Arch(riscv): Error running kextract: kextract file couldn't be generated.
Traceback (most recent call last):
  File "/env_kmax/bin/kismet", line 411, in <module>
    if sample_models: arch.get_kextract() # for sampling
  File "/env_kmax/lib/python3.9/site-packages/kmax/arch.py", line 579, in get_kextract
    self.__ensure_formulas(self.__kextract, self.__kextract_file_delayed_load, self.load_kextract, self.generate_kextract)
  File "/env_kmax/lib/python3.9/site-packages/kmax/arch.py", line 494, in __ensure_formulas
    formula_generation_method()
  File "/env_kmax/lib/python3.9/site-packages/kmax/arch.py", line 782, in generate_kextract
    raise Arch.KextractFormulaGenerationError()
kmax.arch.Arch.KextractFormulaGenerationError: kextract formulas couldn't be generated.

$kmax --version
kmax 4.3.1
```

**Comment by paulgazz** [comment]
Hi @Yujie-Liu, it looks like the reason this is failing is that the riscv architecture was not available in that version of the kernel source (or at least there is no arch/riscv directory, which is what kextract looks for).  Can you confirm that this is the case?  The error messaging is not clear on this though, so I will update to make this clear and avoid the exception.

**Comment by Yujie-Liu** [comment]
Hi @paulgazz, thanks for the info. Yes riscv architecture is indeed not available in v4.9 stable kernel which is the reason of this failure. We'll consider whether the target architecture is supported when running kismet on old kernels, thanks.

**Comment by Yujie-Liu** [comment]
Hi @paulgazz, do I need to close this issue, or keep it open for further enhancement of error message? thanks.

**Comment by paulgazz** [comment]
Hi @Yujie-Liu no need to close.  I converted to enhancement, and will close once we’ve got a pull request in for the error message update.  Thanks for staying on top of this!
