### ISSUE TITLE
kismet verification step throws error when working dir is not inside linux tree

### ISSUE THREAD

**Issue by Yujie-Liu** [paulgazz/kmax#180]
when working dir is inside linux tree:
```
$cd linux
$git checkout 635460a42df915276628f80a77e025a9aa3aa4ad

$kismet --selectees CONFIG_FB_BACKLIGHT --selectors CONFIG_DRM_NOUVEAU -a i386
...
INFO: Architecture kclause formulas were loaded. (183.70sec)
INFO: Identifying the select constructs.
INFO: Identification of the select constructs was done in 0.01sec. 1 constructs were found. unmet safe due to syntactical pass: 0. alarms: 1.
INFO: Doing optimized SAT pass for 1 constructs
INFO: 17:32:02 Optimized SAT pass progress:  1/1 (%100).
INFO: Optimized SAT test was done in 0.01sec. 1 constructs with alarms were checked. unmet safe due to optimized SAT test: 0. alarms: 1.
INFO: Doing precise SAT pass for 1 constructs
INFO: 17:32:04 Precise SAT pass progress:  1/1 (%100).
INFO: Precise SAT test was done in 1.42sec. 1 constructs with alarms were checked. unmet safe due to precise SAT test: 0. alarms: 1.
INFO: During precise SAT test, 1 models were generated.
INFO: Generating test cases (Kconfig config files) for 1 constructs with unmet direct dependency alarms. 1 test cases will be generated.
INFO: Test case files will be written in the following directory: kismet-test-cases/
INFO: 17:32:09 Test case generation progress:  1/1 (%100).
INFO: Test generation was done in 5.15sec. 1 test cases were generated for 1 select constructs with unmet direct dependency alarms.
INFO: Verifying unmet direct dependency alarms using 1 test cases for 1 constructs with unmet direct dependency alarms.
INFO: 17:32:12 Verification from test cases progress:  1/1 (%100).
INFO: Verification was done in 3.20sec. 1 test cases were checked for 1 constructs. 1 of 1 alarms were verified to be true alarms (at least one related test case verified the alarm).
INFO: During verification: for 1 constructs, all test cases verified the related alarm. For 0 constructs, test cases had contradictory results. For 0 constructs, no test case verified the alarm.
INFO: Writing the aggregated summary txt to "kismet_summary_i386.txt".
INFO: Aggregated summary txt was written.
INFO: Writing the summary csv to "kismet_summary_i386.csv".
INFO: Summary csv was written.
```
when working dir is outside linux tree:
```
$cd ..
$kismet --linux-ksrc=linux --selectees CONFIG_FB_BACKLIGHT --selectors CONFIG_DRM_NOUVEAU -a i386
INFO: Computing the build system id for the Linux source..
INFO: Build system id: de5e54511ecd
INFO: Kismet will analyze the select constructs of the architecture "i386" for unmet direct dependency.
INFO: All times reported are measured using Python's time.perf_counter() utility.
INFO: Prefetching the architecture kclause formulas.
INFO: Architecture kclause formulas were loaded. (2.29sec)
INFO: Identifying the select constructs.
INFO: Identification of the select constructs was done in 0.01sec. 1 constructs were found. unmet safe due to syntactical pass: 0. alarms: 1.
INFO: Doing optimized SAT pass for 1 constructs
INFO: 17:35:19 Optimized SAT pass progress:  1/1 (%100).
INFO: Optimized SAT test was done in 0.01sec. 1 constructs with alarms were checked. unmet safe due to optimized SAT test: 0. alarms: 1.
INFO: Doing precise SAT pass for 1 constructs
INFO: 17:35:21 Precise SAT pass progress:  1/1 (%100).
INFO: Precise SAT test was done in 1.42sec. 1 constructs with alarms were checked. unmet safe due to precise SAT test: 0. alarms: 1.
INFO: During precise SAT test, 1 models were generated.
INFO: Generating test cases (Kconfig config files) for 1 constructs with unmet direct dependency alarms. 1 test cases will be generated.
INFO: Test case files will be written in the following directory: kismet-test-cases/
INFO: 17:35:26 Test case generation progress:  1/1 (%100).
INFO: Test generation was done in 5.15sec. 1 test cases were generated for 1 select constructs with unmet direct dependency alarms.
INFO: Verifying unmet direct dependency alarms using 1 test cases for 1 constructs with unmet direct dependency alarms.
Traceback (most recent call last):est cases progress:  0/1 (%0).
  File "/env_kmax/bin/kismet", line 4, in <module>
    __import__('pkg_resources').run_script('kmax==4.4', 'kismet')
  File "/env_kmax/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/env_kmax/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/env_kmax/lib/python3.9/site-packages/kmax-4.4-py3.9-linux-x86_64.egg/EGG-INFO/scripts/kismet", line 1079, in <module>
    main()
  File "/env_kmax/lib/python3.9/site-packages/kmax-4.4-py3.9-linux-x86_64.egg/EGG-INFO/scripts/kismet", line 884, in main
    is_verified = verify_test_case(cfgfilepath, selectee, selector, arch_name)
  File "/env_kmax/lib/python3.9/site-packages/kmax-4.4-py3.9-linux-x86_64.egg/EGG-INFO/scripts/kismet", line 831, in verify_test_case
    os.remove(kismets_copy)
FileNotFoundError: [Errno 2] No such file or directory: 'kismet_verifcopy_udd-i386-CONFIG_FB_BACKLIGHT-CONFIG_DRM_NOUVEAU-0-0.config'
```

**Comment by paulgazz** [comment]
Hi @Yujie-Liu, strangely I am unable to reproduce the bug.  When I run it, even if I remove the `os.remove` call, I get the `kismet_verifcopy_...` file created.  I've created a PR that checks whether the file exists before deleting it, which should at least fix the symptom.

**Comment by paulgazz** [comment]
I've merged the PR and released v4.4.1 with the fix (#181).  Please let me know if it doesn't fix things and I'll investigate more.

Also, I doubt it matters for this bug, but I had to get the linux-stable-rc repo in order to get commit 635460a42df915276628f80a77e025a9aa3aa4ad, since it is not in the linux mainline repo.

**Comment by Yujie-Liu** [comment]
Hi @paulgazz, sorry about I didn't mention the detail of commit 635460a42df915276628f80a77e025a9aa3aa4ad. It is from linux-stable linux-4.19.y branch.
```
tree: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
branch: linux-4.19.y
commit: 635460a42df9 Linux 4.19.256
```
I upgrade kmax to v4.4.1, and the error is gone. Thanks for the fix!
```
$kmax --version
kmax 4.4.1

$kismet --linux-ksrc=linux --selectees CONFIG_FB_BACKLIGHT --selectors CONFIG_DRM_NOUVEAU -a i386
INFO: Computing the build system id for the Linux source..
INFO: Build system id: 4dbfe2164757
INFO: Kismet will analyze the select constructs of the architecture "i386" for unmet direct dependency.
INFO: All times reported are measured using Python's time.perf_counter() utility.
INFO: Prefetching the architecture kclause formulas.
INFO: Architecture kclause formulas were loaded. (3.29sec)
INFO: Identifying the select constructs.
INFO: Identification of the select constructs was done in 0.01sec. 1 constructs were found. unmet safe due to syntactical pass: 0. alarms: 1.
INFO: Doing optimized SAT pass for 1 constructs
INFO: 10:22:15 Optimized SAT pass progress:  1/1 (%100).
INFO: Optimized SAT test was done in 0.01sec. 1 constructs with alarms were checked. unmet safe due to optimized SAT test: 0. alarms: 1.
INFO: Doing precise SAT pass for 1 constructs
INFO: 10:22:16 Precise SAT pass progress:  1/1 (%100).
INFO: Precise SAT test was done in 1.48sec. 1 constructs with alarms were checked. unmet safe due to precise SAT test: 0. alarms: 1.
INFO: During precise SAT test, 1 models were generated.
INFO: Generating test cases (Kconfig config files) for 1 constructs with unmet direct dependency alarms. 1 test cases will be generated.
INFO: Test case files will be written in the following directory: kismet-test-cases/
INFO: 10:22:22 Test case generation progress:  1/1 (%100).
INFO: Test generation was done in 5.89sec. 1 test cases were generated for 1 select constructs with unmet direct dependency alarms.
INFO: Verifying unmet direct dependency alarms using 1 test cases for 1 constructs with unmet direct dependency alarms.
INFO: 10:22:27 Verification from test cases progress:  1/1 (%100).
INFO: Verification was done in 4.10sec. 1 test cases were checked for 1 constructs. 1 of 1 alarms were verified to be true alarms (at least one related test case verified the alarm).
INFO: During verification: for 1 constructs, all test cases verified the related alarm. For 0 constructs, test cases had contradictory results. For 0 constructs, no test case verified the alarm.
INFO: Writing the aggregated summary txt to "kismet_summary_i386.txt".
INFO: Aggregated summary txt was written.
INFO: Writing the summary csv to "kismet_summary_i386.csv".
INFO: Summary csv was written.
```

**Comment by paulgazz** [comment]
No problem, @Yujie-Liu, it wasn’t hard to find.  Glad to hear it’s fixed!
