### ISSUE TITLE
File extension changes in Linux source can lead to klocalizer error 

### ISSUE THREAD

**Issue by lolrepeatlol** [paulgazz/kmax#256]
If a file extension changes type, e.g. from `SOURCE` to `OTHER`, a user may run into an AssertionError in `kmax/patch.py` when using `klocalizer` to repair a configuration file.

### Steps followed
To get a repaired configuration file for a commit range, I followed the steps [here](https://github.com/paulgazz/kmax/blob/master/docs/advanced.md#getting-configuration-files-to-build-commit-ranges-and-using-exclude):

1. Clone the Linux kernel with `git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git` and enter the directory.
2. Create a diff from a range of patches using `git diff {commit1}..{commit2} > patchset.diff`. I initially encountered this issue with the range `fcd63086bc14b1689866d7b0c61958f6b7e48604` to `0db63c0b86e981a1e97d2596d64ceceba1a5470e`.
3. Check out the source code at the latest of the two commits and make `allnoconfig`. 
4. Run `klocalizer` with `klocalizer --repair .config -a x86_64 --include-mutex patchset.diff`.

### What I expected to happen
I expected `klocalizer` to successfully create the repaired configuration file for the range of commits.

### What actually happened
I ran into the following:
```
Traceback (most recent call last):
  File "/home/alexei/.local/bin/klocalizer", line 1726, in <module>
    klocalizerCLI()
  File "/home/alexei/.local/bin/klocalizer", line 529, in klocalizerCLI
    include_mutex_list = parse_units_args(include_mutex_arg)
  File "/home/alexei/.local/bin/klocalizer", line 513, in parse_units_args
    parsed_list.extend(list(get_patch_target_lines(a).items()))
  File "/home/alexei/.local/bin/klocalizer", line 376, in get_patch_target_lines
    r = patch.get_target_c_lines(patch_txt)
  File "/home/alexei/.local/share/pipx/venvs/kmax/lib/python3.8/site-packages/kmax/patch.py", line 246, in get_target_c_lines
    r = get_target_lines(patch_txt)
  File "/home/alexei/.local/share/pipx/venvs/kmax/lib/python3.8/site-packages/kmax/patch.py", line 202, in get_target_lines
    patch_summary = summarize_patch(patch_txt)
  File "/home/alexei/.local/share/pipx/venvs/kmax/lib/python3.8/site-packages/kmax/patch.py", line 107, in summarize_patch
    assert SourceFileType.get_file_type(old_path) == SourceFileType.get_file_type(new_path)
AssertionError
```

## Additional information
* I added the following lines to the code at `kmax/patch.py:107` to get an idea of what's going on:
```
if old_path and new_path:
        print(f"DEBUG: Old path: {old_path}, new path: {new_path}")
        print(f"DEBUG: Old path file type: {SourceFileType.get_file_type(old_path)}, New path file type: {SourceFileType.get_file_type(new_path)}")
        assert SourceFileType.get_file_type(old_path) == SourceFileType.get_file_type(new_path) #affected line
```

I found this:
```
DEBUG: Old path: arch/s390/configs/defconfig, new path: arch/s390/configs/defconfig
DEBUG: Old path file type: SourceFileType.OTHER, New path file type: SourceFileType.OTHER
DEBUG: Old path: arch/s390/crypto/chacha-glue.c, new path: arch/s390/crypto/chacha-glue.c
DEBUG: Old path file type: SourceFileType.SOURCE, New path file type: SourceFileType.SOURCE
DEBUG: Old path: arch/s390/crypto/chacha-s390.S, new path: arch/s390/crypto/chacha-s390.S
DEBUG: Old path file type: SourceFileType.OTHER, New path file type: SourceFileType.OTHER
DEBUG: Old path: arch/s390/crypto/crc32-vx.c, new path: arch/s390/crypto/crc32-vx.c
DEBUG: Old path file type: SourceFileType.SOURCE, New path file type: SourceFileType.SOURCE
DEBUG: Old path: arch/s390/crypto/crc32be-vx.S, new path: arch/s390/crypto/crc32be-vx.c
DEBUG: Old path file type: SourceFileType.OTHER, New path file type: SourceFileType.SOURCE
Traceback (most recent call last):
  File "/home/alexei/.local/bin/klocalizer", line 1726, in <module>
    klocalizerCLI()
```
Note the change in file type from `OTHER` to `SOURCE` when the `.S` file is changed to a `.c` file.

**Comment by lolrepeatlol** [comment]
Fixed with #276.
